export const START_REQUEST = 'START_REQUEST';
export const GET_JSON = 'GET_JSON';
export const GET_SORTDATA = 'GET_SORTDATA';
export const DATA_IS_LOADING='DATA_IS_LOADING';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const USERS_LOGOUT = 'USERS_LOGOUT';
export const SIGN_UP = 'SIGN_UP';

export const USER_UPDATE = 'USER_UPDATE';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';


export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAIL = 'UPLOAD_DOCUMENT_FAIL';

export const GET_ALLVILLATYPES = 'GET_ALLVILLATYPES';

export const GET_ALL_VILLA = 'GET_ALL_VILLA';
export const GET_VILLA_BY_ID = 'GET_VILLA_BY_ID';
export const INSERT_VILLA = 'INSERT_VILLA';
export const UPDATE_VILLA = 'UPDATE_VILLA';

export const GET_ALL_CREW = 'GET_ALL_CREW';
export const GET_CREW_BY_ID = 'GET_CREW_BY_ID';
export const INSERT_CREW = 'INSERT_CREW';
export const UPDATE_CREW = 'UPDATE_CREW';

export const GET_ALL_TARIFF = 'GET_ALL_TARIFF';
export const GET_TARIFF_BY_ID = 'GET_TARIFF_BY_ID';
export const INSERT_TARIFF = 'INSERT_TARIFF';
export const UPDATE_TARIFF = 'UPDATE_TARIFF';
export const GET_TARIFF_BY_VILLA_TYPE = 'GET_TARIFF_BY_VILLA_TYPE';

export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const GET_ALL_BOOKING = 'GET_ALL_BOOKING';
