import 'bootstrap/dist/css/bootstrap.min.css'
import '../static/styles/global.min.css'
import '../static/styles/color.min.css'
import '../static/styles/material-font.min.css'
import '../static/styles/animate.min.css'
import '../static/styles/hover.min.css'
import '../static/styles/style.css'
